version: "3.7"

volumes:
  postgres-data:

services:
  db:
    image: postgres:12
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data