# Generated by Django 3.2.3 on 2021-07-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpictures',
            name='color',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
