# Generated by Django 3.2.3 on 2021-07-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210707_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(default='blue', max_length=20),
            preserve_default=False,
        ),
    ]
