# Generated by Django 3.2.3 on 2022-01-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_shippingaddress_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
    ]
