# Generated by Django 3.2.3 on 2022-01-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_value',
        ),
    ]
