# Generated by Django 3.2.3 on 2022-01-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20220117_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
