# Generated by Django 3.2.3 on 2022-01-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_likedproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedproducts',
            old_name='model',
            new_name='product',
        ),
    ]
