# Generated by Django 3.2.3 on 2021-07-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210707_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='for_kids',
        ),
        migrations.AddField(
            model_name='product',
            name='for_kids',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
