# Generated by Django 3.2.3 on 2021-07-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210707_1517'),
        ('products', '0004_auto_20210707_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
