# Generated by Django 3.2.3 on 2022-01-13 10:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220112_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specs',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=[], null=True, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank=True, default=[], null=True),
        ),
    ]
