# Generated by Django 3.2.3 on 2021-07-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210707_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpictures',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='productpictures',
            name='placeholder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Nike', max_length=40),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
