# Generated by Django 3.2.3 on 2022-01-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220113_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('hiking', 'hiking'), ('running', 'running'), ('sneakers', 'sneakers'), ('basketball', 'basketball')], default=None, max_length=30, null=True),
        ),
    ]
