# Generated by Django 3.2.3 on 2021-07-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpictures',
            old_name='placeholder',
            new_name='color_placeholder',
        ),
        migrations.AddField(
            model_name='productpictures',
            name='primary_placeholder',
            field=models.BooleanField(default=False),
        ),
    ]
