# Generated by Django 3.2.3 on 2022-01-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='title',
            field=models.CharField(default='test1', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='message',
            field=models.TextField(max_length=350),
        ),
    ]
