# Generated by Django 3.2.3 on 2022-01-17 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0010_auto_20220114_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('sport', 'sport'), ('skateboarding', 'skateboarding'), ('sneakers', 'sneakers'), ('lifestyle', 'lifestyle')], default=None, max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'model')},
        ),
    ]
