# Generated by Django 3.2.3 on 2022-01-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rating_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='title',
        ),
    ]
